### ISSUE TITLE
Can't reproduce cifar10/cifar100 results

### ISSUE THREAD

**Issue by WuHyeongDoh** [bollossom/GAC#5]
Hello authors, I'm really interested in your work and thank you for sharing your codes.
But I got some questions on reproducing results on Cifar10/100.
1. when I trained MsResNet18 model based on your instructions on github, the results on Cifar10/100 didn't even get close to the results on the AAAI24 paper. 
2. And using GAC encoder didn't seem to have much improvement on the performance (setting self.GAC=False on Ms_ResNet.py didn't show much accuracy drop on Cifar10).
3. When I changed hyperparameter settings on the github code based on the AAAI24 paper appendix, LIF param (threshold, tau) = (1, 0.5) -> (0.5, 0.25), accuracy showed significant drop.
Could you tell me what am I missing in this experiment? Thank you in advance!

**Comment by bollossom** [comment]
![image](https://github.com/bollossom/GAC/assets/87843847/3d26f9a5-dbc4-4282-9af4-bac44099901a)

**Comment by bollossom** [comment]
Thank you for paying attention to our work. Next I will answer your questions point to point.

1,2 Please recheck whether you have turned on data enhancements such as cutmix or cutout, and whether the kernel size of GAC is 4. At the same time, we have also open sourced the weights of the best results on CIFAR100. 
3，I suppose the change of LIF param is possible because in the image classification task the threshold needs to be a little higher, which is the same as the setting in TET
